### ISSUE TITLE
Run single snapshot deconvolution

### ISSUE THREAD

**Issue by bhazelton** [nicholebarry/MWA_data_analysis#1]
tests deconvolution -> eppsilon
compare to firstpass for same snapshot & other setting the same

**Comment by nicholebarry** [comment]
One snapshot looks good. Good job Ian!
![fhd_nb_decon_nov2015_onetest_obs_id_6296_bh_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/11152218/1be4eba8-89e6-11e5-93a1-176e0f1d3016.png)
