### ISSUE TITLE
perfect cal simulation with imperfect foregrounds, 2 extents, no diffuse

### ISSUE THREAD

**Issue by bhazelton** [nicholebarry/MWA_data_analysis#2]
see if extent matters without diffuse

**Comment by nicholebarry** [comment]
For double the extent, it does appear like the diffuse was causing issues in dirty and model, however the shape of the residual has remained the same, indicating more problems.
![fhd_nb_sim_perfect_cal__beamperchannel_novisflagbasic_modelnoflag_eor_weightfix_ones_maxcalsources_nodiffuse_obs_id_6176_minus_eor_ones_maxcalsources_farextent2_nod_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/11134088/1cc56d28-894f-11e5-8762-1dfdba1db968.png)

**Comment by nicholebarry** [comment]
For triple the extent, we have a similar situation. Dirty and model are different, but residual shape is the same.
![fhd_nb_sim_perfect_cal__beamperchannel_novisflagbasic_modelnoflag_eor_weightfix_ones_maxcalsources_obs_id_6176_minus_eor_ones_maxcalsources_farextent3_nod_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/11152262/65b5ce14-89e6-11e5-8c88-73718887b640.png)
