### ISSUE TITLE
Make new polarized diffuse model to go with current source catalog

### ISSUE THREAD

**Issue by isullivan** [nicholebarry/MWA_data_analysis#5]
We should make a new polarized diffuse model from a current firstpass run using the latest source catalog. If you use the latest version of FHD (v3.5-69-g55ddce7) you can call combine_obs_healpix with your list of fhd file paths and supply the new keyword diffuse_model_filepath= '[path\to\FHD\dir]\FHD\catalog_data\EoR0_polarized_diffuse.sav'. The new keyword will automatically create a diffuse model save file that is ready to be ingested by FHD
I suggest also setting nside=4096

**Comment by nicholebarry** [comment]
Done, will come around in email.
